baseURL: 'https://binick.github.io'
title: a developer's journey to the cloud
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false
buildExpired: false
enableEmoji: true

googleAnalytics: UA-181166811-1
# disqusShortname: binick-github-io

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  author: Nicola Biancolini

  env: production
  description: "a developer's journey to the cloud"

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: auto
  displayFullLangName: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: false
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    favicon: /favicon.ico
    disableHLJS: true

  label:
    text: "a developer's journey..."
    icon: /me.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set

  # home-info mode
  homeInfoParams:
    Title: "... to the cloud"
    # Content: Photo by [sendi gibran](https://unsplash.com/@sendi_r_gibran?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText") on [Unsplash](https://unsplash.com/images/nature/cloud?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)

  socialIcons:
    - name: github
      url: 'https://github.com/binick'
    - name: stackoverflow
      url: 'https://stackoverflow.com/users/7684814/binick'
    - name: twitter
      url: 'https://twitter.com/nbiancolini'
    - name: linkedin
      url: 'https://www.linkedin.com/in/nicolabiancolini'
    - name: rss
      url: '/index.xml'

  editPost:
    URL: "https://github.com/binick/binick.github.io/tree/main/content"
    Text: "✏️"
    appendFilePath: true

#   analytics:
#     google:
#       SiteVerificationTag: "XYZabc"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
    pygmentsUseClasses: true
    tabWidth: 2

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 10
    - name: Search
      url: /search/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 10
      
taxonomies:
  category: categories
  tag: tags
  series: series
