name: build

on:
  pull_request:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: NPM install
        run: npm install

      - name: Build site
        run: hugo -e e2e-testing -s ./src --minify

      - name: E2E tests
        run: npm run test
        continue-on-error: true
        if: false

      - name: Upload a11y analysis results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: artifacts/test-results/a11y
          category: axe-core
          wait-for-processing: false
        if: false
