name: build
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v5

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: NPM install
        run: npm install && npm exec playwright install --with-deps

      - name: Build site
        run: hugo -e e2e-testing -s ./src --minify

      - name: E2E tests
        run: npm run test
        continue-on-error: true
      
      - name: Generate HTML report
        run: npx github-actions-ctrf artifacts/test-results/ctrf-report.json
        if: always()
