name: ship

on:
  pull_request:
    types: 
      - closed

  workflow_dispatch:

  workflow_call:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo -e production -s ./src --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./artifacts/public

  update-profile:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Delay profile update
        run: sleep 60s

      - name: Update profile page
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.AUTOBOT_TOKEN }}" \
          https://api.github.com/repos/binick/binick/dispatches \
          -d '{ "event_type":"update-readme" }'
