name: ship

on:
  pull_request:
    types: 
      - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo -e production -s ./src --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.AUTOBOT_TOKEN }}
          publish_dir: ./artifacts/public

  update-profile:
    uses: binick/binick/.github/workflows/update-readme-with-latest-blob-posts.yml@main
